# Generated by Django 5.2 on 2025-04-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coquetel',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
