# Generated by Django 5.2 on 2025-04-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_coquetel_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='coquetel',
            name='ingredientes',
            field=models.TextField(null=True),
        ),
    ]
