# Generated by Django 5.2 on 2025-04-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_coquetel_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coquetel',
            name='preco',
        ),
        migrations.AddField(
            model_name='coquetel',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='coquetel',
            name='ingredientes',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
