# Generated by Django 5.2 on 2025-04-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0004_remove_coquetel_preco_coquetel_preco_venda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coquetel',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='coquetel',
            name='recipiente',
            field=models.CharField(choices=[('ld', 'Long Drink'), ('otr', 'On The Rocks'), ('tac', 'Taça')], default=''),
        ),
    ]
