# Generated by Django 5.2 on 2025-04-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0005_coquetel_preco_custo_coquetel_recipiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('funcao', models.CharField(choices=[('brt', 'bartender'), ('coz', 'cozinheiro'), ('gar', 'garçom'), ('cai', 'caixa'), ('ger', 'gerente')], default='')),
                ('cpf', models.CharField(default=None, max_length=11, null=True, unique=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
            ],
        ),
    ]
