# Generated by Django 5.2 on 2025-04-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0006_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ingredientes', models.TextField(max_length=200, null=True)),
                ('tempo_preparo', models.TimeField(default=0.0)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
    ]
