# Generated by Django 5.2 on 2025-04-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0007_porcoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porcoes',
            name='tempo_preparo',
        ),
        migrations.AddField(
            model_name='porcoes',
            name='adicional',
            field=models.CharField(choices=[('Cal', 'Calabresa'), ('Mus', 'Mussarela'), ('Bac', 'Bacon'), ('Che', 'Cheddar'), ('Cat', 'Catupiry')], default=''),
        ),
        migrations.AlterField(
            model_name='porcoes',
            name='ingredientes',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
