# Generated by Django 5.2 on 2025-04-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0008_remove_porcoes_tempo_preparo_porcoes_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porcoes',
            name='adicional',
            field=models.CharField(choices=[('', '---'), ('Cal', 'Calabresa'), ('Mus', 'Mussarela'), ('Bac', 'Bacon'), ('Che', 'Cheddar'), ('Cat', 'Catupiry')], default=''),
        ),
    ]
