# Generated by Django 5.2 on 2025-04-22 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0009_alter_porcoes_adicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('pago', models.BooleanField()),
                ('forma_pagamento', models.CharField(choices=[('Cre', 'Crédito'), ('Deb', 'Débito'), ('Pix', 'Pix'), ('Din', 'Dinheiro')])),
                ('datahora', models.DateTimeField()),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bar.funcionario')),
                ('coqueteis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bar.coquetel')),
            ],
        ),
        migrations.CreateModel(
            name='Porcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ingredientes', models.TextField(max_length=300, null=True)),
                ('adicional', models.CharField(blank=True, choices=[('', '---'), ('Cal', 'Calabresa'), ('Mus', 'Mussarela'), ('Bac', 'Bacon'), ('Che', 'Cheddar'), ('Cat', 'Catupiry')], default='')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Porcoes',
        ),
        migrations.AddField(
            model_name='pedido',
            name='porcoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bar.porcao'),
        ),
    ]
