# Generated by Django 5.2 on 2025-04-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0010_pedido_porcao_delete_porcoes_pedido_porcoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coquetel',
            options={'verbose_name_plural': 'Coqueteis'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='porcao',
            options={'verbose_name_plural': 'Porções'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='datahora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
